models/alert.py
from typing import Dict
import uuid
from dataclasses import dataclass, field
from models.item import Item
from models.user import User
from models.model import Model
from libs.mailgun import Mailgun


@dataclass(eq=False)
# This will prevent us from doing two alert objects
class Alert(Model):
    # collection = "alerts"
    # collection string is converted into a data class.
    # It is not going to be included in Init Method and default is going to be "Alerts".
    collection: str = field(init=False, default="alerts")
    alert_name: str
    item_id: str
    price_limit: float
    user_email: str
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)
    # But the data class can't take care of self.item which is not passed as a parameter
    # Also, the lamda methods can return a value, but can't access the parameter values.
    # to solve this there is __post_init__ method
    def __post_init__(self):
        self.item = Item.get_by_id(self.item_id)
        self.user = User.find_by_email(self.user_email)

    def json(self) -> Dict:
        return {
            "_id": self._id,
            "alert_name": self.alert_name,
            "item_id": self.item_id,
            "price_limit": self.price_limit,
            "user_email": self.user_email
        }

    def load_item_price(self) -> float:
        self.item.load_price()
        return self.item.price

    def notify_if_price_reached(self) -> None:
        print(f"NOTIFY : {self}")
        if self.item.price < self.price_limit:
            print(f"Item ID: {self.item._id} Name: {self.item.item_name} has reached a price under {self.price_limit}. Latest price: {self.item.price}.")
            resp = Mailgun.send_email(
                email=[self.user_email],
                subject=f"Notification for {self.item.item_name}",
                text=f"Your alert {self.item.item_name} has reached a price under {self.price_limit}. The latest price is {self.item.price}. Go to this address to check your item: {self.item.url}.",
                html=f'<p>Your alert {self.alert_name} has reached a price under {self.price_limit}.</p><p>The latest price is {self.item.price}. Click <a href="{self.item.url}>here</a> to purchase your item.</p>'
            )
            print(f"Mail Sent Successfully {resp}")

views/alerts_bp.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from models.alert import Alert
from models.item import Item
from models.store import Store
from models.user import requires_login


alert_blueprint = Blueprint('bp_alerts', __name__)


@alert_blueprint.route('/')
# Include Function Decorator
@requires_login
def index():
    print(f"ALERT BP {session['rks_email']}")
    # alerts_present = Alert.all()
    alerts_present = Alert.find_many_by('user_email', session['rks_email'])
    return render_template('alerts/alert_index.html', alerts=alerts_present)

@alert_blueprint.route('/new', methods=['GET', 'POST'])
@requires_login
def new_alert():
    if request.method == 'POST':
        # process the Data from the Form.
        # access the Item_ID, & Item_Price from the form
        alert_name = request.form['name_of_alert']
        item_url = request.form['item_url']
        price_limit = float(request.form['price_limit'])  # Str needs to converted to Float

        store = Store.find_by_url(item_url)

        item = Item(alert_name, item_url, store.tag_name, store.query)
        print(f"ITEM LOAD PRICE::: {item}")
        item.load_price()
        print(f"ITEM PRICE is found = {item.price}")
        print(f"ITEM AFTER PRICE is found ===== {item}")
        print(f"URL = {item_url}")

        my_item = Item.get_by_name(alert_name)
        print(f"FIND ITEM found ===== {my_item}")

        if my_item is None:
            print("SAVING ITEM ::::::::::: INTO MONGO")
            item.save_to_mongo()
        else:
            # assign found item's item._id to be passed to Alert module.
            item._id = my_item._id

        # item.save_to_mongo()

        # The warning below is fine as we are using but not changing the protected variable
        #print(f"Aname: {alert_name}  IT_id = {item._id}  2ndIT_id = {my_item._id}  PRICE = {price_limit}  MAIL: {session['rks_email']}")
        Alert(alert_name, item._id, price_limit, session['rks_email']).save_to_mongo()

    return render_template('alerts/new_alert.html')

@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@requires_login
def edit_alert(alert_id):
    alert_by_id = Alert.get_by_id(alert_id)

    if request.method == 'POST':
        price_limit = float(request.form['price_limit'])
        alert_by_id.price_limit = price_limit
        alert_url = alert_by_id.item.url

        # We'l now update the Alert Entry in DB.
        alert_by_id.save_to_mongo()
        # Call below computes the URL to go to index method inside the current blueprint using '.'
        return redirect(url_for('.index'))

    return render_template('alerts/edit_alert.html',alert=alert_by_id)

@alert_blueprint.route('/delete/<string:alert_id>')
@requires_login
# No GET or POST method is required as we are not dealing with any form here
def delete_alert(alert_id):
    my_alert = Alert.get_by_id(alert_id)
    if my_alert.user_email == session['rks_email']:
        my_alert.remove_from_mongo()
    return redirect(url_for('.index'))

templates/alerts/alert_index.html
{% extends "base.html" %}

{% block rk_com_content %}
<header>
    <h1>List of Alerts</h1>
</header>
<section>
    <div class="list-group">
        {% for alert in alerts %}
        <div class="list-group-item">
            <h4 class="list-group-item-heading">{{ alert.alert_name}}</h4>
            <p >
                <a href="{{ alert.item.url }}">{{ alert.item_id }} (last price {{ alert.item.price}})</a>
            </p>
            <a class="btn btn-secondary" href="{{ url_for('bp_alerts.edit_alert', alert_id=alert._id) }}">
                Edit
            </a>
            <a class="btn btn-danger" href="{{ url_for('bp_alerts.delete_alert', alert_id=alert._id) }}">
                Delete
            </a>
        </div>
        {% endfor %}
    </div>
    <a class="btn btn-primary mt-3" href="{{ url_for('bp_alerts.new_alert') }}">
        Create new
    </a>
</section>
{% endblock %}

templates/alerts/edit_alert.html
{% extends "base.html" %}
{% block rk_com_content %}
<header>
    <h1>Update Alert</h1>
</header>
<section class="update-alert-form">
    <form method="post">
        <div class="form-group">
            <label for="alert_name">Alert Name</label>
            <input type="text" class="form-control" id="alert_name" name="name_of_alert" value="{{ alert.alert_name }}" disabled>
        </div>
        <div class="form-group">
            <label for="item_url">Item URL</label>
            <input type="text" class="form-control" id="item_url" name="item_url" value="{{ alert.item.url }}" disabled>
        </div>
        <div class="form-group">
            <label for="price_limit">Price limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="120" value="{{ alert.price_limit }}"
                aria-describedby="priceLimitHelp">
            <small id="priceLimitHelp" class="form-text text-muted">
                Under which price for the item would you like to get notified?
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</section>
{% endblock %}

templates/alerts/new_alert.html
{% extends "base.html" %}
{% block rk_com_content %}
<header>
    <h1>Create Alert</h1>
</header>
<section class="create-alert-form">
    <form method="post">
        <div class="form-group">
            <label for="alert_name">Alert Name</label>
            <input type="text" class="form-control" id="alert_name" name="name_of_alert" placeholder="chair"
                   aria-describedby="alertNameHelp"/>
            <small id="alertNameHelp" class="form-text text-muted">
                Specify a Name of your Item for which Alert is being created
            </small>
        </div>
        <div class="form-group">
            <label for="item_url">Item URL</label>
            <input type="text" class="form-control" id="item_url" name="item_url" placeholder="https://..."
                aria-describedby="itemURLHelp">
            <small id="itemURLHelp" class="form-text text-muted">
                What is the URL of the element you wish to make an alert for?
            </small>
        </div>
        <div class="form-group">
            <label for="price_limit">Price limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="120"
                aria-describedby="priceLimitHelp">
            <small id="priceLimitHelp" class="form-text text-muted">
                Under which price for the item would you like to get notified?
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</section>
{% endblock %}