models/store.py
from typing import Dict
from dataclasses import dataclass, field
import uuid
import re
from models.model import Model


@dataclass(eq=False)
class Store(Model):
    collection: str = field(init=False, default="stores")
    store_name: str
    url_prefix: str
    tag_name: str
    query: Dict
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def __post_init__(self):
        self.price = None

    # Convert a Python Object to JSON to be stored in MongoDB.
    def json(self) -> Dict:
        return {
            "_id": self._id,
            "store_name": self.store_name,
            "url_prefix": self.url_prefix,
            "tag_name": self.tag_name,
            "query": self.query
        }

    @classmethod
    def get_by_name(cls, sname: str) -> "Store":
        return cls.find_one_by("store_name", sname)

    @classmethod
    def get_by_url_prefix(cls, url_prefix: str) -> "Store":
        url_regex = {"$regex": '^{}'.format(url_prefix)}  # make sure it starts with URL Prefix.
        return cls.find_one_by("url_prefix", url_regex)

    @classmethod
    def find_by_url(cls, url: str) -> "Store":
        """
        Return a store from a url like "http://www.johnlewis.com/item/sdfj4h5g4g21k.html"
        :param url: The item's URL
        :return: a Store
        """
        pattern = re.compile(r"(https?://.*?/)")  # ?: Match both http or https://something/
        match = pattern.search(url)
        url_prefix = match.group(1)
        return cls.get_by_url_prefix(url_prefix)

views/stores_bp.py
import json
from flask import Blueprint, render_template, request, redirect, url_for
from models.alert import Alert
from models.item import Item
from models.store import Store
from models.user import requires_login, requires_admin

store_blueprint = Blueprint('bp_stores', __name__)


@store_blueprint.route('/')
@requires_login
def index():
    stores_present = Store.all()
    print("RKS: STORE INDEX ALL done")
    return render_template('stores/store_index.html', stores=stores_present)

@store_blueprint.route('/new', methods=['GET', 'POST'])
@requires_admin
def new_store():
    if request.method == 'POST':
        # process the Data from the Form.
        # access the Item_ID, & Item_Price from the form
        store_name = request.form['name_of_store']
        url_prefix = request.form['nm_url_prefix']
        tag_name = request.form['name_tag']
        query = json.loads(request.form['nm_query'])

        Store(store_name, url_prefix, tag_name, query).save_to_mongo()

    return render_template('stores/new_store.html')



@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@requires_admin
def edit_store(store_id):
    store_by_id = Store.get_by_id(store_id)

    if request.method == 'POST':
        store_name = request.form['name_of_store']
        url_prefix = request.form['nm_url_prefix']
        tag_name = request.form['name_tag']
        query = json.loads(request.form['nm_query'])

        # Modify the Store object
        store_by_id.store_name = store_name
        store_by_id.url_prefix = url_prefix
        store_by_id.tag_name = tag_name
        store_by_id.query = query

        # We'll now update the Store Entry in DB.
        store_by_id.save_to_mongo()
        # Call below computes the URL to go to index method inside the current blueprint using '.'
        return redirect(url_for('.index'))

    # somehow if we do not use Dumps below, the Query gets passed to HTML as '' single quotes
    # this then is discarded by json.loads().
    my_query = store_by_id.query
    store_by_id.query = json.dumps(my_query)

    return render_template('stores/edit_store.html',store=store_by_id)

@store_blueprint.route('/delete/<string:store_id>')
@requires_admin
def delete_store(store_id):
    Store.get_by_id(store_id).remove_from_mongo()
    return redirect(url_for('.index'))

templates/stores/edit_store.html
{% extends "base.html" %}
{% block rk_com_content %}
<header>
    <h1>Update Store</h1>
</header>
<section class="update-store-form">
    <form method="post">
        <div class="form-group">
            <label for="store_name">Store Name</label>
            <input type="text" class="form-control" id="store_name" name="name_of_store" placeholder="John Lewis" value="{{ store.store_name }}"
                   aria-describedby="storeNameHelp"/>
            <small id="storeNameHelp" class="form-text text-muted">
                Specify a Name of the Store
            </small>
        </div>
        <div class="form-group">
            <label for="url_prefix">Item URL</label>
            <input type="text" class="form-control" id="url_prefix" name="nm_url_prefix" placeholder="https://..." value="{{ store.url_prefix }}"
                aria-describedby="urlPrefixHelp">
            <small id="urlPrefixHelp" class="form-text text-muted">
                What URL will all its items start with?
            </small>
        </div>
        <div class="form-group">
            <label for="tag_name">HTML Tag Name</label>
            <input type="text" class="form-control" id="tag_name" name="name_tag" placeholder="span" value="{{ store.tag_name }}"
                aria-describedby="priceTagHelp">
            <small id="priceTagHelp" class="form-text text-muted">
                What HTML tag contains the price information for this item in this store?
            </small>
        </div>
        <div class="form-group">
            <label for="query">HTML Query</label>
            <input type="text" class="form-control" id="query" name="nm_query" placeholder='{"class": "price price--large"}' value="{{ store.query }}"
                   aria-describedby="queryHelp">
            <small id="queryHelp" class="form-text text-muted">
                What attributes are on the element that contains the Price? This is so we can find it on the page.
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</section>
{% endblock %}

templates/stores/new_store.html
{% extends "base.html" %}
{% block rk_com_content %}
<header>
    <h1>Create Store</h1>
</header>
<section class="create-store-form">
    <form method="post">
        <div class="form-group">
            <label for="store_name">Store Name</label>
            <input type="text" class="form-control" id="store_name" name="name_of_store" placeholder="John Lewis"
                   aria-describedby="storeNameHelp"/>
            <small id="storeNameHelp" class="form-text text-muted">
                Specify a Name of the Store
            </small>
        </div>
        <div class="form-group">
            <label for="url_prefix">Item URL</label>
            <input type="text" class="form-control" id="url_prefix" name="nm_url_prefix" placeholder="https://..."
                aria-describedby="urlPrefixHelp">
            <small id="urlPrefixHelp" class="form-text text-muted">
                What URL will all its items start with?
            </small>
        </div>
        <div class="form-group">
            <label for="tag_name">HTML Tag Name</label>
            <input type="text" class="form-control" id="tag_name" name="name_tag" placeholder="span"
                aria-describedby="priceTagHelp">
            <small id="priceTagHelp" class="form-text text-muted">
                What HTML tag contains the price information for this item in this store?
            </small>
        </div>
        <div class="form-group">
            <label for="query">HTML Query</label>
            <input type="text" class="form-control" id="query" name="nm_query" placeholder='{"class": "price price--large"}'
                   aria-describedby="queryHelp">
            <small id="queryHelp" class="form-text text-muted">
                What attributes are on the element that contains the Price? This is so we can find it on the page.
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</section>
{% endblock %}

templates/stores/store_index.html
{% extends "base.html" %}

{% block rk_com_content %}
<header>
    <h1>Stores</h1>
</header>
<section>
    <div class="list-group">
        {% for store in stores %}
        <div class="list-group-item">
            <h4 class="list-group-item-heading">{{ store.store_name }}</h4>
            <p >
                For URLs starting with {{ store.url_prefix }}
            </p>
            {% if session['rks_email'] == config.ADMIN %}
            <a class="btn btn-secondary" href="{{ url_for('bp_stores.edit_store', store_id=store._id) }}">
                Edit
            </a>
            <a class="btn btn-danger" href="{{ url_for('bp_stores.delete_store', store_id=store._id) }}">
                Permanently Delete store
            </a>
            {% endif %}

        </div>
        {% endfor %}
    </div>
    {% if session['rks_email'] == config.ADMIN %}
    <a class="btn btn-primary mt-3" href="{{ url_for('bp_stores.new_store') }}">
        Create new
    </a>
    {% endif %}
</section>
{% endblock %}