views/alerts_bp.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from models.alert import Alert
from models.item import Item
from models.store import Store
from models.user import requires_login


alert_blueprint = Blueprint('bp_alerts', __name__)


@alert_blueprint.route('/')
# Include Function Decorator
@requires_login
def index():
    print(f"ALERT BP {session['rks_email']}")
    # alerts_present = Alert.all()
    alerts_present = Alert.find_many_by('user_email', session['rks_email'])
    return render_template('alerts/alert_index.html', alerts=alerts_present)

@alert_blueprint.route('/new', methods=['GET', 'POST'])
@requires_login
def new_alert():
    if request.method == 'POST':
        # process the Data from the Form.
        # access the Item_ID, & Item_Price from the form
        alert_name = request.form['name_of_alert']
        item_url = request.form['item_url']
        price_limit = float(request.form['price_limit'])  # Str needs to converted to Float

        store = Store.find_by_url(item_url)

        item = Item(alert_name, item_url, store.tag_name, store.query)
        print(f"ITEM LOAD PRICE::: {item}")
        item.load_price()
        print(f"ITEM PRICE is found = {item.price}")
        print(f"ITEM AFTER PRICE is found ===== {item}")
        print(f"URL = {item_url}")

        my_item = Item.get_by_name(alert_name)
        print(f"FIND ITEM found ===== {my_item}")

        if my_item is None:
            print("SAVING ITEM ::::::::::: INTO MONGO")
            item.save_to_mongo()
        else:
            # assign found item's item._id to be passed to Alert module.
            item._id = my_item._id

        # item.save_to_mongo()

        # The warning below is fine as we are using but not changing the protected variable
        #print(f"Aname: {alert_name}  IT_id = {item._id}  2ndIT_id = {my_item._id}  PRICE = {price_limit}  MAIL: {session['rks_email']}")
        Alert(alert_name, item._id, price_limit, session['rks_email']).save_to_mongo()

    return render_template('alerts/new_alert.html')

@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@requires_login
def edit_alert(alert_id):
    alert_by_id = Alert.get_by_id(alert_id)

    if request.method == 'POST':
        price_limit = float(request.form['price_limit'])
        alert_by_id.price_limit = price_limit
        alert_url = alert_by_id.item.url

        # We'l now update the Alert Entry in DB.
        alert_by_id.save_to_mongo()
        # Call below computes the URL to go to index method inside the current blueprint using '.'
        return redirect(url_for('.index'))

    return render_template('alerts/edit_alert.html',alert=alert_by_id)

@alert_blueprint.route('/delete/<string:alert_id>')
@requires_login
# No GET or POST method is required as we are not dealing with any form here
def delete_alert(alert_id):
    my_alert = Alert.get_by_id(alert_id)
    if my_alert.user_email == session['rks_email']:
        my_alert.remove_from_mongo()
    return redirect(url_for('.index'))

views/stores_bp.py
import json
from flask import Blueprint, render_template, request, redirect, url_for
from models.alert import Alert
from models.item import Item
from models.store import Store
from models.user import requires_login, requires_admin

store_blueprint = Blueprint('bp_stores', __name__)


@store_blueprint.route('/')
@requires_login
def index():
    stores_present = Store.all()
    print("RKS: STORE INDEX ALL done")
    return render_template('stores/store_index.html', stores=stores_present)

@store_blueprint.route('/new', methods=['GET', 'POST'])
@requires_admin
def new_store():
    if request.method == 'POST':
        # process the Data from the Form.
        # access the Item_ID, & Item_Price from the form
        store_name = request.form['name_of_store']
        url_prefix = request.form['nm_url_prefix']
        tag_name = request.form['name_tag']
        query = json.loads(request.form['nm_query'])

        Store(store_name, url_prefix, tag_name, query).save_to_mongo()

    return render_template('stores/new_store.html')



@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@requires_admin
def edit_store(store_id):
    store_by_id = Store.get_by_id(store_id)

    if request.method == 'POST':
        store_name = request.form['name_of_store']
        url_prefix = request.form['nm_url_prefix']
        tag_name = request.form['name_tag']
        query = json.loads(request.form['nm_query'])

        # Modify the Store object
        store_by_id.store_name = store_name
        store_by_id.url_prefix = url_prefix
        store_by_id.tag_name = tag_name
        store_by_id.query = query

        # We'll now update the Store Entry in DB.
        store_by_id.save_to_mongo()
        # Call below computes the URL to go to index method inside the current blueprint using '.'
        return redirect(url_for('.index'))

    # somehow if we do not use Dumps below, the Query gets passed to HTML as '' single quotes
    # this then is discarded by json.loads().
    my_query = store_by_id.query
    store_by_id.query = json.dumps(my_query)

    return render_template('stores/edit_store.html',store=store_by_id)

@store_blueprint.route('/delete/<string:store_id>')
@requires_admin
def delete_store(store_id):
    Store.get_by_id(store_id).remove_from_mongo()
    return redirect(url_for('.index'))

views/users_bp.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from models.user import User, UserErrors

user_blueprint = Blueprint('bp_users', __name__)

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():

    if(request.method == 'POST'):
        my_email = request.form['nm_email']
        my_password = request.form['nm_password']

        try:
            User.register_user(my_email, my_password)
            session['rks_email'] = my_email
            return my_email

        except UserErrors.UserError as e:
            return e.message

    return render_template('users/register.html')

@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():

    if(request.method == 'POST'):
        my_email = request.form['nm_email']
        my_password = request.form['nm_password']

        try:
            User.is_login_valid(my_email, my_password)
            session['rks_email'] = my_email
            return my_email

        except UserErrors.UserError as e:
            return e.message

    return render_template('users/login.html')

@user_blueprint.route('/logout')
def logout():
    session['email'] = None
    return redirect(url_for('.login_user'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Price Alert</title>
</head>
<body>
    <div class="content container mt-2">
        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
            <a class="navbar-brand" href="#">Pricing Service</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                <a class="nav-item nav-link" href="{{ url_for('bp_stores.index') }}">Stores</a>
                <a class="nav-item nav-link" href="{{ url_for('bp_alerts.index') }}">Alerts</a>
                <a class="nav-item nav-link" href="{{ url_for('bp_users.login_user') }}">Log in</a>
                <a class="nav-item nav-link" href="{{ url_for('bp_users.register_user') }}">Sign up</a>
                </div>
            </div>
        </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{category}}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div class=""mt-3">
    </div>

    {% block rk_com_content %}

    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block rk_com_content %}
    <div class="jumbotron">
        <h1 class="display-4">Pricing Service</h1>
        <p class="lead">We scan online store websites to alert you of price drops in items that interest you.</p>
        <hr class="my-4">
        <p>Just sign up, and get started by adding the URL of an item that you wish to track. We'll do the rest!</p>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('bp_users.register_user') }}" role="button">Get started</a></p>
    </div>
{% endblock %}